# Generated by Django 5.1.5 on 2025-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasterreport',
            name='user',
        ),
        migrations.AddField(
            model_name='disasterreport',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='disasterreport',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='disasterreport',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
    ]
